apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/madhav8890/test-argo-repo.git'
        revision: HEAD
        directories:
          - path: charts/* # Matches all subdirectories under charts
  template:
    metadata:
      name: '{{path.basename}}' # Use the directory name as the application name
    spec:
      project: default
      source:
        repoURL: 'https://github.com/your-org/your-repo.git'
        targetRevision: HEAD
        path: '{{path}}' # Path to the specific chart directory
        helm:
          valueFiles:
            - '{{path}}/values.yaml' # Custom values file for each chart
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}' # Deploy each application in its own namespace or adjust as needed
      syncPolicy:
        automated:
          prune: true
          selfHeal: true