apiVersion: apps/v1
kind: Deployment
metadata:
  name: chart2-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chart2
  template:
    metadata:
      labels:
        app: chart2
    spec:
      containers:
      - name: httpd
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
