apiVersion: apps/v1
kind: Deployment
metadata:
  name: chart1-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chart1
  template:
    metadata:
      labels:
        app: chart1
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
