apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
  namespace: default
spec:
  selector:
    app: app1  # The selector matches the pods with the label 'app: my-app'
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8080  # Port inside the container that the service forwards to
  type: ClusterIP  # Exposes the service only inside the cluster
